[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
ts-rs = "6.2.1"
html-escape = "0.2.13"

[dev-dependencies]
pretty_assertions = "1.3.0"
